# Generated by Django 4.1.1 on 2022-09-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdminId', models.AutoField(primary_key=True, serialize=False)),
                ('AdminName', models.CharField(max_length=500)),
                ('AdminPassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookId', models.AutoField(primary_key=True, serialize=False)),
                ('BookName', models.CharField(max_length=500)),
                ('BookCategory', models.CharField(max_length=500)),
                ('BookAuthor', models.CharField(max_length=500)),
            ],
        ),
    ]
