# Generated by Django 4.1.1 on 2022-09-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
