# Generated by Django 4.1.1 on 2022-09-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0002_admin_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='AdminEmail',
            field=models.EmailField(default=0, max_length=45),
            preserve_default=False,
        ),
    ]
